name: Playwright and K6 Tests by RK

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  playwright-tests:
    name: Playwright Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm test
        env:
          CI: true

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload Ortoni report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ortoni-report
          path: ortoni-report/
          retention-days: 30

  k6-performance-tests:
    name: K6 Performance Tests
    runs-on: ubuntu-latest
    needs: playwright-tests
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install k6
        run: |
          curl -L https://github.com/grafana/k6/releases/download/v0.46.0/k6-v0.46.0-linux-amd64.tar.gz -o k6.tar.gz
          tar -xzf k6.tar.gz
          sudo cp k6-v0.46.0-linux-amd64/k6 /usr/local/bin

      - name: Run K6 performance tests
        run: k6 run tests/perfromance/auth.k6.js

      - name: Upload K6 results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: k6-results
          path: k6-results/
          retention-days: 7
